package cpanel

const (
	ModuleAddonDomain      = "AddonDomain"
	ModuleBlockIP          = "BlockIP"
	ModuleCron             = "Cron"
	ModuleDenyIP           = "DenyIp"
	ModuleDirectoryIndexes = "DirectoryIndexes"
	ModuleDirectoryPrivacy = "DirectoryPrivacy"
	ModuleDNS              = "DNS"
	ModuleDomainInfo       = "DomainInfo"
	ModuleDynamicDNS       = "DynamicDNS"
	ModuleEmail            = "Email"
	ModuleFileman          = "Fileman"
	ModuleFtp              = "Ftp"
	ModuleMysql            = "Mysql"
	ModuleMysqlFE          = "MysqlFE"
	ModuleMime             = "Mime"
	ModulePark             = "Park"
	ModulePostgresql       = "Postgresql"
	ModuleSubDomain        = "SubDomain"
	ModuleTokens           = "Tokens"
	ModuleVariables        = "Variables"
	ModuleVersionControl   = "VersionControl"
)
